export const SESSION_SET_CREATE_FORM_EMAIL = 'SESSION_SET_CREATE_FORM_EMAIL';
export const SESSION_SET_CREATE_FORM_PASSWORD = 'SESSION_SET_CREATE_FORM_PASSWORD';
export const SESSION_SET_TOKEN = 'SESSION_SET_TOKEN';
export const SESSION_SET_STATUS = 'SESSION_SET_STATUS';

export const TASK_SET_CREATE_FORM_NAME = 'TASK_SET_CREATE_FORM_NAME';
export const TASK_SET_CREATE_FORM_PRIORITY = 'TASK_SET_CREATE_FORM_PRIORITY';
export const TASK_SET_CREATE_FORM_SCHEDULE = 'TASK_SET_CREATE_FORM_SCHEDULE';
export const TASK_SET_CREATE_VISIBLE = 'TASK_SET_CREATE_VISIBLE';
export const TASK_SET_UPDATE_FORM_NAME = 'TASK_SET_UPDATE_FORM_NAME';
export const TASK_SET_UPDATE_FORM_PRIORITY = 'TASK_SET_UPDATE_FORM_PRIORITY';
export const TASK_SET_UPDATE_FORM_SCHEDULE = 'TASK_SET_UPDATE_FORM_SCHEDULE';
export const TASK_SET_UPDATE_FORM_STATUS = 'TASK_SET_UPDATE_FORM_STATUS';
export const TASK_SET_UPDATE_VISIBLE = 'TASK_SET_UPDATE_VISIBLE';
export const TASK_SET_UPDATE_ID = 'TASK_SET_UPDATE_ID';
export const TASK_SET_UPDATE_INDEX = 'TASK_SET_UPDATE_INDEX';
export const TASK_SET_REMOVE_VISIBLE = 'TASK_SET_REMOVE_VISIBLE';
export const TASK_SET_REMOVE_ID = 'TASK_SET_REMOVE_ID';
export const TASK_SET_REMOVE_INDEX = 'TASK_SET_REMOVE_INDEX';

export const TASK_INITIALIZE_TASKS = 'TASK_INITIALIZE_TASKS';
export const TASK_PUSH_TASK = 'TASK_PUSH_TASK';
export const TASK_REMOVE_TASK = 'TASK_REMOVE_TASK';
export const TASK_UPDATE_TASK = 'TASK_UPDATE_TASK';

export const USER_SET_CREATE_FORM_EMAIL = 'USER_SET_CREATE_FORM_EMAIL';
export const USER_SET_CREATE_FORM_NAME = 'USER_SET_CREATE_FORM_NAME';
export const USER_SET_CREATE_FORM_PASSWORD = 'USER_SET_CREATE_FORM_PASSWORD';
export const USER_SET_CREATE_FORM_PASSWORD_CONFIRM = 'USER_SET_CREATE_FORM_PASSWORD_CONFIRM';
export const USER_SET_UPDATE_FORM_EMAIL = 'USER_SET_UPDATE_FORM_EMAIL';
export const USER_SET_UPDATE_FORM_NAME = 'USER_SET_UPDATE_FORM_NAME';
export const USER_SET_UPDATE_FORM_PASSWORD = 'USER_SET_UPDATE_FORM_PASSWORD';
export const USER_SET_UPDATE_VISIBLE = 'USER_SET_UPDATE_VISIBLE';
